"""Status classification for extracted page content.

Moved from ``content/sanitize.py`` with four behavior changes:
- ``_normalize`` applies NFKC before phrase matching (mojibake-proofing).
- Typed-JSON skips carry ``cacheable=False`` on error HTTP statuses (a 404
  JSON body is valid JSON but must not poison the page cache).
- Gopher-style junk ratios (datatrove) feed a ``partial`` verdict.
- ``wall_from_classification`` consumes a ``ClassificationResult`` — the
  caller classifies once; no internal re-classification.
"""

from __future__ import annotations

import json
import logging
import re
import unicodedata
from collections.abc import Mapping
from dataclasses import dataclass

from ..content.artifact import ContentStatus
from ..utils.observability import emit_observability_event
from ..utils.text_clean import PROSE_UNICODE_MAP, _MD_LINK_RE, strip_jina_frontmatter


LOGGER = logging.getLogger(__name__)

_TYPED_SKIP = frozenset({"json", "jsonl", "csv", "tsv", "rss", "atom", "xml"})
_PASSWORD_RE = re.compile(r"""type\s*=\s*['"]password['"]""", re.IGNORECASE)
_EMPTY_BULLET_RE = re.compile(r"^\s*[\*\-]\s*$")
_ADVERTISEMENT_RE = re.compile(r"(?i)^\s*advertisement\s*$")
_NOT_LOADED_RE = re.compile(r"(?i)not yet fully loaded")
_WIN_THRESHOLD = 0.5
_LONG_DOC_WORDS = 150
_PHRASE_WEIGHT = 0.25
_PHRASE_WEIGHT_STRONG = 0.5


@dataclass(frozen=True)
class ClassificationResult:
    status: ContentStatus
    reason: str | None
    cacheable: bool
    score: float = 0.0


_BLOCK_PATTERNS: tuple[str, ...] = (
    "access denied",
    "verify you are human",
    "checking your browser",
    "please enable javascript",
    "please turn javascript on",
    "cloudflare",
    "forbidden",
    "captcha",
    "your request has been blocked",
    "you have been blocked",
    "just a moment",
    "attention required",
    "checking if the site connection is secure",
    "verify you are a human",
    "verifying you are human",
    "enable javascript and cookies to continue",
    "unusual traffic from your computer network",
    "are you a robot",
    "press & hold",
    "ddos protection by",
    "ddos-guard",
    "request unsuccessful. incapsula incident id",
    "generated by cloudfront (cloudfront)",
    "the request could not be satisfied",
    "you don't have permission to access",
    "access to this page has been denied",
    "blocked by network security",
    "you have been temporarily blocked",
    "too many requests",
)

_LOGIN_WALL_PATTERNS: tuple[str, ...] = (
    "sign in to continue",
    "sign in to view",
    "log in to continue",
    "log in to view",
    "please login",
    "please log in",
    "create an account to",
    "sign up to continue",
    "you need to be logged in",
    "login required",
    "authentication required",
    "this content is for registered users",
    "sign in to github",
    "log in to github",
    "you must log in",
    "you need to log in",
    "login to continue",
    "register to continue",
    "sign in to your account",
    "forgot your password",
    "you are not signed in",
)

_PAYWALL_PATTERNS: tuple[str, ...] = (
    "subscribe to read",
    "subscribe to continue",
    "premium content",
    "premium article",
    "upgrade to access",
    "upgrade your plan",
    "this is a subscriber-only",
    "you've reached your free article limit",
    "you have reached your limit",
    "members only",
    "become a member",
    "subscribe to continue reading",
    "member-only story",
    "subscribers only",
    "only for subscribers",
    "subscribe to unlock",
    "create a free account to continue reading",
    "already a subscriber",
)

_ERROR_PATTERNS: tuple[str, ...] = (
    "err_unsafe_port",
    "err_connection_refused",
    "err_connection_timed_out",
    "err_name_not_resolved",
    "this site can't be reached",
    "chrome-error://chromewebdata",
    "404 not found",
    "page not found",
    "500 internal server error",
    "503 service unavailable",
    "403 forbidden",
    "502 bad gateway",
    "the requested url was not found",
    "this page doesn't exist",
    "this page does not exist",
    "an error occurred",
    "something went wrong",
    "internal server error",
    "gateway time-out",
    "gateway timeout",
    "error establishing a database connection",
    "whitelabel error page",
    "site temporarily unavailable",
    "service temporarily unavailable",
    "the page you requested was not found",
    "deployment_not_found",
    "function_not_found",
    "fastly error",
    "application error",
)

# Phrases that essentially never appear inside genuine article content; a
# single hit is enough to classify. Generic phrases need accumulating hits,
# an HTTP status boost, or a short page to reach the win threshold.
_STRONG_PHRASES: dict[str, frozenset[str]] = {
    "error_page": frozenset(
        {
            "err_unsafe_port",
            "err_connection_refused",
            "err_connection_timed_out",
            "err_name_not_resolved",
            "chrome-error://chromewebdata",
            "this site can't be reached",
            "error establishing a database connection",
            "whitelabel error page",
            "deployment_not_found",
            "function_not_found",
            "fastly error",
        }
    ),
    "access_blocked": frozenset(
        {
            "verify you are human",
            "verify you are a human",
            "verifying you are human",
            "just a moment",
            "attention required",
            "checking your browser",
            "checking if the site connection is secure",
            "enable javascript and cookies to continue",
            "unusual traffic from your computer network",
            "are you a robot",
            "press & hold",
            "ddos protection by",
            "ddos-guard",
            "request unsuccessful. incapsula incident id",
            "generated by cloudfront (cloudfront)",
            "the request could not be satisfied",
            "you don't have permission to access",
            "access to this page has been denied",
            "blocked by network security",
        }
    ),
    "login_wall": frozenset(),
    "paywall": frozenset(
        {
            "subscribe to continue reading",
            "member-only story",
            "subscribers only",
            "only for subscribers",
            "create a free account to continue reading",
        }
    ),
}

_COOKIE_CONSENT_WORDS = frozenset({"cookie", "cookies", "gdpr", "ccpa"})
_COOKIE_CONSENT_PHRASE_RE = re.compile(
    r"(?i)\b(?:privacy policy|data protection"
    r"|cookie (?:policy|consent|settings|preferences|notice)"
    r"|we use cookies|this site uses cookies|accept all cookies"
    r"|manage preferences|do not sell)\b"
)
_COOKIE_CONSENT_ACTION_RE = re.compile(
    r"(?i)\b(?:accept|allow|reject|decline|manage|customize|consent|agree"
    r"|opt(?:[- ]?in|[- ]?out)|we use|this site uses|value your privacy)\b"
)

_SPA_SHELL_PATTERNS: tuple[str, ...] = (
    "enable javascript",
    "please turn javascript on",
    "loading...",
    "this application requires javascript",
    "you need to enable javascript to run this app",
    "doesn't work properly without javascript",
    "this app works best with javascript",
    "this website requires javascript",
    "requires javascript to run",
    "# root",
    "# app",
)
_SPA_SHELL_MAX_WORDS = 150
_SPA_GENERIC_PHRASES = frozenset({"# root", "# app"})

_REDIRECT_URL_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"^\s*https?://\S+\s*$"),
    re.compile(r"^\s*redirect(?:ing|ed)?\s+to\s+https?://\S+", re.IGNORECASE),
    re.compile(
        r"^\s*(?:301|302|303|307|308)\s*(?:moved|found|redirect)?\s*:?\s*https?://\S+",
        re.IGNORECASE,
    ),
)


def _compile_phrases(phrases: tuple[str, ...]) -> tuple[tuple[str, re.Pattern[str]], ...]:
    compiled: list[tuple[str, re.Pattern[str]]] = []
    for phrase in phrases:
        parts = [re.escape(part) for part in phrase.split()]
        compiled.append((phrase, re.compile(r"\s+".join(parts), re.IGNORECASE)))
    return tuple(compiled)


_ERROR_RE = _compile_phrases(_ERROR_PATTERNS)
_BLOCK_RE = _compile_phrases(_BLOCK_PATTERNS)
_LOGIN_RE = _compile_phrases(_LOGIN_WALL_PATTERNS)
_PAYWALL_RE = _compile_phrases(_PAYWALL_PATTERNS)
_SPA_RE = _compile_phrases(_SPA_SHELL_PATTERNS)


def _normalize(text: str) -> str:
    """NFKC/case/whitespace/typography-normalized text for phrase matching."""
    normalized = unicodedata.normalize("NFKC", text)
    return " ".join(normalized.translate(PROSE_UNICODE_MAP).lower().split())


def _phrase_hits(text: str, compiled: tuple[tuple[str, re.Pattern[str]], ...]) -> list[str]:
    hits: list[str] = []
    for phrase, regex in compiled:
        if regex.search(text):
            hits.append(phrase)
            if len(hits) >= 3:
                break
    return hits


def _weighted_score(hits: list[str], strong: frozenset[str]) -> float:
    return sum(_PHRASE_WEIGHT_STRONG if hit in strong else _PHRASE_WEIGHT for hit in hits)


def _header_challenge(headers: Mapping[str, str] | None, word_count: int = 10**9) -> bool:
    if not headers:
        return False
    for key, value in headers.items():
        if key.lower() == "cf-mitigated" and str(value).strip().lower() == "challenge":
            return True
        # Cloudflare-fronted host returning a near-empty render: Turnstile/interstitial
        # that the client rendered without an explicit cf-mitigated header.
        if (
            key.lower() == "server"
            and "cloudflare" in str(value).strip().lower()
            and word_count < 25
        ):
            return True
    return False


def _is_typed_skip(markdown: str, source_type: str | None) -> bool:
    if (source_type or "").lower() in _TYPED_SKIP:
        return True
    body = strip_jina_frontmatter(markdown).lstrip()
    if not (body.startswith("{") or body.startswith("[")):
        return False
    try:
        json.loads(body)
    except Exception:
        return False
    return True


def _non_printable_ratio(text: str) -> float:
    if not text:
        return 0.0
    bad = 0
    for ch in text:
        cp = ord(ch)
        if cp == 0xFFFD:
            bad += 1
        elif cp == 0x00:
            bad += 1
        elif cp < 0x20 and cp not in (0x09, 0x0A, 0x0D):
            bad += 1
    return bad / len(text)


def _cookie_boilerplate_ratio(normalized: str) -> float:
    """Cookie-banner vocabulary density; requires a consent action cue.

    Ordinary pages that merely discuss cookies/privacy carry no action verbs
    and score 0.0.
    """
    words = normalized.split()
    if not words:
        return 0.0
    if not _COOKIE_CONSENT_ACTION_RE.search(normalized):
        return 0.0
    cookie_words = sum(1 for word in words if word.strip(".,;:!?\"'()[]") in _COOKIE_CONSENT_WORDS)
    return (cookie_words + 2 * len(_COOKIE_CONSENT_PHRASE_RE.findall(normalized))) / len(words)


def chrome_ratio(markdown: str) -> float:
    """Ratio of chrome lines (empty bullets, ads, duplicates) over non-blank lines."""
    lines = [line for line in markdown.splitlines() if line.strip()]
    total = max(len(lines), 1)
    empty_bullet = sum(1 for line in lines if _EMPTY_BULLET_RE.match(line))
    advertisement = sum(1 for line in lines if _ADVERTISEMENT_RE.match(line))
    duplicate_copies = 0
    previous: str | None = None
    for line in lines:
        if line == previous:
            duplicate_copies += 1
        previous = line
    return (empty_bullet + advertisement + duplicate_copies) / total


def _gopher_signals(markdown: str) -> dict[str, float]:
    """Gopher-style junk ratios (datatrove gopher_quality/repetition filters).

    Digit-normalized duplicate comparison so "2024", "2025" rows collapse to
    one repeated template line.
    """
    lines = [line.strip() for line in markdown.splitlines() if line.strip()]
    if not lines:
        return {
            "avg_word_length": 0.0,
            "symbol_word_ratio": 0.0,
            "bullet_fraction": 0.0,
            "ellipsis_fraction": 0.0,
            "duplicate_line_fraction": 0.0,
        }
    words = markdown.split()
    n_words = max(len(words), 1)
    avg_word_length = sum(len(w) for w in words) / n_words
    symbol_count = markdown.count("#") + markdown.count("...")
    symbol_word_ratio = symbol_count / n_words
    bullet = sum(1 for line in lines if _LIST_MARKER_LINE_RE.match(line))
    ellipsis = sum(1 for line in lines if line.endswith("...") or line.endswith("…"))
    seen: set[str] = set()
    duplicate_extra = 0
    for line in lines:
        key = re.sub(r"\d+", "#", line).casefold()
        if key in seen:
            duplicate_extra += 1
        else:
            seen.add(key)
    total = len(lines)
    return {
        "avg_word_length": avg_word_length,
        "symbol_word_ratio": symbol_word_ratio,
        "bullet_fraction": bullet / total,
        "ellipsis_fraction": ellipsis / total,
        "duplicate_line_fraction": duplicate_extra / total,
    }


_LIST_MARKER_LINE_RE = re.compile(r"^(?:[-*+]|\d{1,9}[.)])\s")

# Gopher paper thresholds (arXiv 2112.11446, Table A1) for the signals we
# reuse; word-count/avg-length rules stay out (too aggressive for pages).
_GOPHER_MAX_SYMBOL_WORD_RATIO = 0.1
_GOPHER_MAX_BULLET_FRACTION = 0.9
_GOPHER_MAX_ELLIPSIS_FRACTION = 0.3
_GOPHER_MAX_DUPLICATE_FRACTION = 0.3


def _emit_classification_event(
    result: ClassificationResult,
    markdown: str,
    normalized: str,
    **extra: float | int | str | bool | None,
) -> None:
    emit_observability_event(
        LOGGER,
        "content.status.classified",
        status=result.status,
        reason=result.reason,
        cacheable=result.cacheable,
        markdown_chars=len(markdown),
        word_count=len(normalized.split()),
        **extra,  # type: ignore[arg-type]
    )


def _category_scores(
    markdown: str,
    *,
    http_status: int | None,
    challenge: bool,
) -> dict[str, tuple[float, list[str]]]:
    """Additive phrase scores plus explicit HTTP-status/boost precedence.

    Status mapping is unambiguous: 401 -> login, 403/429 -> blocked,
    404/410/5xx -> error, challenge -> blocked. Body phrases accumulate at
    0.25 (generic) or 0.5 (strong) per hit; a category wins at >= 0.5.
    """
    error_hits = _phrase_hits(markdown, _ERROR_RE)
    block_hits = _phrase_hits(markdown, _BLOCK_RE)
    login_hits = _phrase_hits(markdown, _LOGIN_RE)
    paywall_hits = _phrase_hits(markdown, _PAYWALL_RE)
    error_score = _weighted_score(error_hits, _STRONG_PHRASES["error_page"])
    block_score = _weighted_score(block_hits, _STRONG_PHRASES["access_blocked"])
    login_score = _weighted_score(login_hits, _STRONG_PHRASES["login_wall"])
    paywall_score = _weighted_score(paywall_hits, _STRONG_PHRASES["paywall"])
    if http_status == 401:
        login_score += 0.8
    elif http_status in {403, 429}:
        block_score += 0.8
    elif http_status is not None and (http_status in {404, 410} or http_status >= 500):
        error_score += 0.8
    if challenge:
        block_score += 0.8
    if _PASSWORD_RE.search(markdown):
        login_score += 0.7
    return {
        "error_page": (error_score, error_hits),
        "access_blocked": (block_score, block_hits),
        "login_wall": (login_score, login_hits),
        "paywall": (paywall_score, paywall_hits),
    }


def classify_markdown(
    markdown: str,
    source_type: str | None = None,
    http_status: int | None = None,
    headers: Mapping[str, str] | None = None,
) -> ClassificationResult:
    """Classify extracted page content for quality/block/error signals."""
    normalized = _normalize(markdown)
    if not normalized:
        result = ClassificationResult(status="error", reason="empty_content", cacheable=False)
        _emit_classification_event(result, markdown, normalized)
        return result

    if _is_typed_skip(markdown, source_type):
        # A valid typed body on an error status (404 JSON) must not be cached.
        cacheable = http_status is None or 200 <= http_status < 300
        result = ClassificationResult(status="success", reason=None, cacheable=cacheable)
        _emit_classification_event(result, markdown, normalized)
        return result

    word_count = len(normalized.split())
    challenge = _header_challenge(headers, word_count)
    folded = unicodedata.normalize("NFKC", markdown).translate(PROSE_UNICODE_MAP)
    scores = _category_scores(folded, http_status=http_status, challenge=challenge)
    veto = word_count > _LONG_DOC_WORDS and http_status not in {401, 403, 429} and not challenge

    if not veto:
        for name in ("error_page", "access_blocked", "login_wall", "paywall"):
            score, hits = scores[name]
            if score < _WIN_THRESHOLD:
                continue
            phrase = hits[0] if hits else name
            if name == "error_page":
                result = ClassificationResult(
                    status="error", reason=f"error_page:{phrase}", cacheable=False, score=score
                )
            elif name == "access_blocked":
                result = ClassificationResult(
                    status="blocked",
                    reason=f"access_blocked:{phrase}",
                    cacheable=False,
                    score=score,
                )
            elif name == "login_wall":
                result = ClassificationResult(
                    status="blocked", reason=f"login_wall:{phrase}", cacheable=False, score=score
                )
            else:
                result = ClassificationResult(
                    status="blocked", reason=f"paywall:{phrase}", cacheable=False, score=score
                )
            _emit_classification_event(result, markdown, normalized)
            return result

    for regex in _REDIRECT_URL_PATTERNS:
        if regex.search(normalized):
            result = ClassificationResult(status="partial", reason="redirect_only", cacheable=False)
            _emit_classification_event(result, markdown, normalized)
            return result

    bad_char_ratio = _non_printable_ratio(markdown)
    if bad_char_ratio > 0.15:
        result = ClassificationResult(status="error", reason="garbled_content", cacheable=False)
        _emit_classification_event(
            result, markdown, normalized, bad_char_ratio=round(bad_char_ratio, 4)
        )
        return result

    cookie_ratio = _cookie_boilerplate_ratio(normalized)
    if cookie_ratio > 0.4:
        result = ClassificationResult(
            status="partial", reason="cookie_boilerplate", cacheable=False
        )
        _emit_classification_event(
            result, markdown, normalized, cookie_ratio=round(cookie_ratio, 4)
        )
        return result

    if word_count < _SPA_SHELL_MAX_WORDS:
        spa_hits = [hit for hit in _phrase_hits(folded, _SPA_RE) if hit not in _SPA_GENERIC_PHRASES]
        if not spa_hits and word_count <= 20:
            spa_hits = [hit for hit in _phrase_hits(folded, _SPA_RE) if hit in _SPA_GENERIC_PHRASES]
    else:
        spa_hits = []
    if spa_hits:
        result = ClassificationResult(
            status="partial", reason=f"spa_shell:{spa_hits[0]}", cacheable=False
        )
        _emit_classification_event(result, markdown, normalized)
        return result

    not_loaded = bool(_NOT_LOADED_RE.search(markdown))
    if chrome_ratio(markdown) > 0.5 or (not_loaded and word_count < 80):
        result = ClassificationResult(
            status="partial", reason="chrome_boilerplate", cacheable=False
        )
        _emit_classification_event(result, markdown, normalized)
        return result

    signals = _gopher_signals(markdown)
    if (
        signals["duplicate_line_fraction"] > _GOPHER_MAX_DUPLICATE_FRACTION
        or signals["ellipsis_fraction"] > _GOPHER_MAX_ELLIPSIS_FRACTION
        or signals["bullet_fraction"] > _GOPHER_MAX_BULLET_FRACTION
        or signals["symbol_word_ratio"] > _GOPHER_MAX_SYMBOL_WORD_RATIO
    ):
        result = ClassificationResult(status="partial", reason="gopher_junk", cacheable=False)
        _emit_classification_event(
            result,
            markdown,
            normalized,
            duplicate_line_fraction=round(signals["duplicate_line_fraction"], 4),
            ellipsis_fraction=round(signals["ellipsis_fraction"], 4),
            bullet_fraction=round(signals["bullet_fraction"], 4),
            symbol_word_ratio=round(signals["symbol_word_ratio"], 4),
        )
        return result

    if word_count < 40 and len(_MD_LINK_RE.findall(markdown)) >= 5:
        result = ClassificationResult(status="partial", reason="navigation_only", cacheable=False)
        _emit_classification_event(result, markdown, normalized)
        return result

    if word_count < 80:
        result = ClassificationResult(status="partial", reason="too_short", cacheable=False)
        _emit_classification_event(result, markdown, normalized)
        return result

    result = ClassificationResult(status="success", reason=None, cacheable=True)
    _emit_classification_event(result, markdown, normalized)
    return result


def wall_from_classification(
    classified: ClassificationResult,
    error: dict[str, object] | None,
) -> dict[str, object] | None:
    """Project access-wall metadata from a ClassificationResult.

    The caller classifies once and passes the result; no re-classification
    happens here.
    """
    if classified.status == "success":
        return None
    code = str((error or {}).get("code") or "")
    reason = classified.reason or ""
    confidence = "high" if classified.score else "medium"
    if reason.startswith("login_wall") or code.startswith("login_wall"):
        return {"kind": "login", "confidence": confidence, "retryable": False}
    if reason.startswith("paywall") or code.startswith("paywall"):
        return {"kind": "paywall", "confidence": confidence, "retryable": False}
    lowered = f"{reason} {code}".lower()
    if (
        reason.startswith("access_blocked")
        or code.startswith("access_blocked")
        or "captcha" in lowered
        or "challenge" in lowered
    ):
        return {"kind": "bot", "confidence": confidence, "retryable": False}
    if reason.startswith("spa_shell"):
        return {"kind": "js_shell", "confidence": "medium", "retryable": True}
    return None
