"""Telemetry package with OTEL instrumentation helpers."""

# ruff: noqa: F401, F403, F405
from __future__ import annotations

import httpx

from .attributes import *
from .constants import (
    LOGS_AVAILABLE,
    _OTEL_SDK_AVAILABLE,
    _initialized,
)
from ._internal import (
    _LoggingExporterProxy,
    _parse_otlp_headers,
    _probe_otlp_endpoint,
    _resolve_otlp_headers,
    _resolve_otlp_signal_endpoint,
    _resolve_phoenix_headers,
    build_grafana_cloud_headers,
    build_hf_space_headers,
)
from .init import init_telemetry, init_telemetry_background
from .metrics import *
from .records_ai import *
from .records_circuit import *
from .records_content import *
from .records_core import *
from .records_rerank import *
from .span_enhancements import *
from .spans import *

__all__ = [
    # Initialization
    "init_telemetry",
    "init_telemetry_background",
    "get_tracer",
    "get_meter",
    "get_search_total_metric",
    # Basic metrics recording
    "record_provider_call",
    "record_search_request",
    "record_merge",
    "record_cache_lookup",
    "record_mcp_tool_call",
    "record_content_resolution",
    "record_content_fallback",
    "record_content_error",
    # RRF merge metrics (NEW)
    "record_rrf_merge",
    "record_rrf_score",
    # Query rewrite metrics (NEW)
    "record_query_rewrite",
    # Reranking metrics (NEW)
    "record_rerank_stage",
    "record_diversity_removal",
    # Circuit breaker metrics (NEW)
    "record_circuit_breaker_state",
    "record_circuit_breaker_event",
    # Tool-specific metrics (NEW)
    "record_gemini_search",
    "record_perplexity_search",
    "record_youtube_transcript",
    "record_youtube_search",
    "record_tool_details",
    # Query quality metrics (Phase 2)
    "record_query_length",
    "record_domain_diversity",
    # Span creation
    "create_search_span",
    "create_provider_span",
    "create_llm_operation_span",
    "create_chain_span",
    "create_mcp_tool_span",
    "create_content_span",
    "create_merge_span",
    "create_query_rewrite_span",
    "create_rerank_span",
    "create_circuit_breaker_span",
    "create_cache_span",
    # Span enhancement
    "add_results_to_span",
    "add_query_rewrite_variants_to_span",
    "add_rrf_merge_details_to_span",
    "add_rerank_scores_to_span",
    "set_span_error",
    "set_span_success",
    # Semantic convention constants
    "HTTP_REQUEST_METHOD",
    "URL_FULL",
    "SERVER_ADDRESS",
    "SERVER_PORT",
    "HTTP_RESPONSE_STATUS_CODE",
    "HTTP_RESPONSE_BODY_SIZE",
    "ERROR_TYPE",
    "NETWORK_PROTOCOL_VERSION",
    "MCP_METHOD_NAME",
    "MCP_SERVER_NAME",
    "MCP_SESSION_ID",
    "MCP_RESOURCE_URI",
    "GEN_AI_TOOL_NAME",
    "GEN_AI_OPERATION_NAME",
    "GEN_AI_SYSTEM",
    "RPC_SYSTEM",
    "RPC_JSONRPC_VERSION",
    "PROVIDER_NAME",
    "PROVIDER_STATUS",
    "PROVIDER_RESULT_COUNT",
    "PROVIDER_DURATION_MS",
    "PROVIDER_ERROR_TYPE",
    "SEARCH_QUERY",
    "SEARCH_NUM_RESULTS_REQUESTED",
    "SEARCH_NUM_RESULTS_RETURNED",
    "SEARCH_PROVIDERS_REQUESTED",
    "SEARCH_PROVIDERS_USED",
    "SEARCH_MERGE_ALGORITHM",
    "CACHE_TYPE",
    "CACHE_HIT",
    "CACHE_LOOKUP_DURATION_MS",
    "CONTENT_STAGE",
    "CONTENT_STATUS",
    "CONTENT_SIZE_BYTES",
    "CONTENT_URL",
    "CONTENT_WORD_COUNT",
    "CONTENT_EXTRACTION_METHOD",
    "CONTENT_FINAL_STAGE",
    "CONTENT_FALLBACK_COUNT",
    "RRF_INPUT_LISTS",
    "RRF_INPUT_TOTAL",
    "RRF_OUTPUT_TOTAL",
    "RRF_DISCARDED_COUNT",
    "RRF_OVERLAP_RATE",
    "RRF_PROVIDER_CONTRIBUTION",
    "RRF_PROVIDER_WEIGHT",
    "RRF_SCORE",
    "RRF_BEST_RANK",
    "RRF_PROVIDERS",
    "REWRITE_POLICY",
    "REWRITE_VARIANT_COUNT",
    "REWRITE_HAS_PRECISION_SIGNALS",
    "REWRITE_MODEL",
    "REWRITE_VARIANT_TYPE",
    "REWRITE_VARIANT_TEXT",
    "RERANK_STAGE",
    "RERANK_INPUT_COUNT",
    "RERANK_OUTPUT_COUNT",
    "RERANK_REMOVED_COUNT",
    "RERANK_RELEVANCE_SCORE",
    "RERANK_MODEL",
    "RERANK_DIVERSITY_THRESHOLD",
    "RERANK_SIMILARITY_SCORE",
    "RERANK_BI_ENCODER_SCORE",
    "CIRCUIT_STATE",
    "CIRCUIT_FAILURE_COUNT",
    "CIRCUIT_LAST_FAILURE_TIME",
    "CIRCUIT_EVENT",
    "CIRCUIT_FAILURE_THRESHOLD",
    "RESULT_POSITION",
    "RESULT_PROVIDER_COUNT",
    "RESULT_RRF_SCORE",
    "RESULT_PROVIDER_SOURCES",
    "RESULT_HAS_SNIPPET",
    "RESULT_DOMAIN",
    "RESULT_TITLE",
    "RESULT_URL",
    "GEMINI_GROUNDING_QUERIES",
    "GEMINI_GROUNDING_CHUNKS",
    "GEMINI_STRUCTURED_OUTPUT",
    "PERPLEXITY_DEPTH",
    "PERPLEXITY_SOURCE_COUNT",
    "PERPLEXITY_MODEL",
    "YOUTUBE_FORMAT",
    "YOUTUBE_LANGUAGE",
    "YOUTUBE_IS_TRANSLATED",
    "YOUTUBE_DURATION_SECONDS",
    "YOUTUBE_BACKEND_USED",
    "YOUTUBE_SEARCH_BACKEND",
    "STATUS_SUCCESS",
    "STATUS_ERROR",
    "STATUS_TIMEOUT",
    "PROVIDER_SEARXNG",
    "PROVIDER_DDG",
    "PROVIDER_GEMINI",
    "PROVIDER_TAVILY",
    "PROVIDER_BRAVE",
    "PROVIDER_JINA",
    "CONTENT_STAGE_STACKEXCHANGE",
    "CONTENT_STAGE_GITHUB",
    "CONTENT_STAGE_WIKIPEDIA",
    "CONTENT_STAGE_ARXIV",
    "CONTENT_STAGE_HTTP_EXTRACT",
    "CONTENT_STAGE_NODRIVER",
]
