from __future__ import annotations


def build_candidate_survival_view_sql(target: str) -> str:
    return f"""
        CREATE OR REPLACE VIEW {target}.vw_candidate_survival AS
        SELECT
            run_key,
            recorded_at,
            'provider' AS stage,
            provider AS source_provider,
            json_extract_string(payload_json, '$.query') AS query,
            link AS url,
            title,
            snippet,
            domain,
            NULL AS providers_json,
            NULL AS provider_count,
            score,
            NULL AS raw_score,
            NULL AS source_engines_json,
            NULL AS category,
            published_date,
            branch_index,
            json_extract_string(payload_json, '$.branch_query') AS branch_query,
            NULL AS branch_weight,
            rank AS result_index,
            json_extract_string(payload_json, '$.candidate_id') AS candidate_id,
            json_extract_string(payload_json, '$.canonical_result_id') AS canonical_result_id,
            json_extract_string(payload_json, '$.tool_call_id') AS tool_call_id
        FROM {target}.provider_candidates
        UNION ALL
        SELECT
            run_key,
            recorded_at,
            'branch' AS stage,
            NULL AS source_provider,
            json_extract_string(payload_json, '$.query') AS query,
            link AS url,
            title,
            snippet,
            domain,
            providers,
            provider_count,
            score,
            NULL AS raw_score,
            NULL AS source_engines_json,
            NULL AS category,
            NULL AS published_date,
            branch_index,
            json_extract_string(payload_json, '$.branch_query') AS branch_query,
            NULL AS branch_weight,
            candidate_rank AS result_index,
            candidate_id,
            canonical_result_id,
            json_extract_string(payload_json, '$.tool_call_id') AS tool_call_id
        FROM {target}.branch_candidates
        UNION ALL
        SELECT
            run_key,
            recorded_at,
            'merged' AS stage,
            NULL AS source_provider,
            NULL AS query,
            link AS url,
            title,
            snippet,
            domain,
            providers,
            provider_count,
            rrf_score AS score,
            NULL AS raw_score,
            NULL AS source_engines_json,
            NULL AS category,
            NULL AS published_date,
            NULL AS branch_index,
            NULL AS branch_query,
            NULL AS branch_weight,
            rank AS result_index,
            NULL AS candidate_id,
            NULL AS canonical_result_id,
            NULL AS tool_call_id
        FROM {target}.merged_candidates
        UNION ALL
        SELECT
            run_key,
            recorded_at,
            stage AS stage,
            NULL AS source_provider,
            NULL AS query,
            link AS url,
            NULL AS title,
            NULL AS snippet,
            NULL AS domain,
            NULL AS providers_json,
            NULL AS provider_count,
            score_after AS score,
            score_before AS raw_score,
            NULL AS source_engines_json,
            NULL AS category,
            NULL AS published_date,
            NULL AS branch_index,
            NULL AS branch_query,
            NULL AS branch_weight,
            COALESCE(rank_after, rank_before) AS result_index,
            json_extract_string(payload_json, '$.candidate_id') AS candidate_id,
            json_extract_string(payload_json, '$.canonical_result_id') AS canonical_result_id,
            NULL AS tool_call_id
        FROM {target}.rerank_candidates
        UNION ALL
        SELECT
            run_key,
            recorded_at,
            'final' AS stage,
            NULL AS source_provider,
            NULL AS query,
            link AS url,
            title,
            snippet,
            domain,
            NULL AS providers_json,
            provider_count,
            final_score AS score,
            NULL AS raw_score,
            NULL AS source_engines_json,
            NULL AS category,
            NULL AS published_date,
            NULL AS branch_index,
            NULL AS branch_query,
            NULL AS branch_weight,
            rank AS result_index,
            json_extract_string(payload_json, '$.candidate_id') AS candidate_id,
            json_extract_string(payload_json, '$.canonical_result_id') AS canonical_result_id,
            NULL AS tool_call_id
        FROM {target}.final_results
        UNION ALL
        SELECT
            run_key,
            recorded_at,
            'returned' AS stage,
            NULL AS source_provider,
            NULL AS query,
            link AS url,
            title,
            snippet,
            domain,
            providers AS providers_json,
            provider_count,
            score,
            NULL AS raw_score,
            NULL AS source_engines_json,
            NULL AS category,
            NULL AS published_date,
            NULL AS branch_index,
            NULL AS branch_query,
            NULL AS branch_weight,
            result_rank AS result_index,
            candidate_id,
            canonical_result_id,
            tool_call_id
        FROM {target}.web_search_response_results
    """
