"""Plain-English descriptions for the analytics explorer tabs and database objects."""

from __future__ import annotations

# ── Plain-English tab descriptions ───────────────────────────────────────────
# These are shown at the top of each tab so you always know what you're looking at.

_TAB_DESCRIPTIONS: dict[str, str] = {
    "events": (
        "Every event the server fires — searches, rewrites, reranks, fetches, and cache lookups. "
        "Sorted newest first (up to 200 rows). "
        "Use the search box to filter by query text, tool name, or provider."
    ),
    "cache": (
        "'Hits' = a cached answer was reused (fast, no API call). "
        "'Misses' = fresh results had to be fetched from a search provider. "
        "Higher hit rates mean lower latency and lower API costs. "
        "'Avg Similarity' shows how close the cached query was to the new one."
    ),
    "providers": (
        "Which search backends were queried (Brave, SearXNG, Tavily, Gemini, …), "
        "how many result rows they contributed, and their average quality score. "
        "'Provider Overlap' counts how many backends agreed on the same result — "
        "higher overlap generally means higher confidence."
    ),
    "errors": (
        "Failures, timeouts, and exceptions, grouped by error type so you can spot recurring problems. "
        "A high 'Occurrences' count on one error type means something needs attention. "
        "Click column headers to sort."
    ),
    "schema": (
        "Every table and view that exists in the analytics DuckDB file. "
        "Each row is one column. Use 'Type' to distinguish raw tables from derived views. "
        "The 'What it stores' column explains the purpose of the table or view in plain English."
    ),
}

# ── Human-readable descriptions for every object in the DB ───────────────────

_OBJECT_DESCRIPTIONS: dict[str, str] = {
    # Raw tables
    "quick_web_search_runs": (
        "One row per terminal quick_web_search invocation, recording status, duration, "
        "citation totals, parameters, and token usage."
    ),
    "quick_web_search_citations": (
        "Individual citations returned by quick_web_search, including title, URL, snippet, "
        "publish date, and excerpts."
    ),
    "gemini_search_runs": (
        "One row per terminal Gemini grounded search execution, capturing query, mode, answer, "
        "model used, token totals, grounding counts, and fallback chain."
    ),
    "gemini_search_sources": (
        "Grounding sources and URL citations returned by Gemini search runs."
    ),
    "code_search_runs": (
        "One row per terminal code_search execution with query plan parameters, provider counts, "
        "result counts, outcome, and duration."
    ),
    "code_search_providers": (
        "Aggregate provider response facts for code_search, including hits returned, requests made, "
        "outcome, and compiled queries."
    ),
    "code_search_diagnostics": (
        "Provider and budget diagnostics emitted during code_search execution."
    ),
    "code_search_hits": (
        "Internal ranked code_search evidence items before public projection, including scores, "
        "components, line coordinates, and hydration flags."
    ),
    "code_search_hit_variants": (
        "Contributing planner-variant and provider associations for final code search hits."
    ),
    "code_search_query_variants": (
        "Query variants and their classification generated by the query planner for code search."
    ),
    "code_search_repositories": (
        "Discovered repository candidates with GitHub metadata, stars, forks, and supporting proof hit counts."
    ),
    "code_search_rerank": ("Cloud rerank execution outcomes and candidate counts for code search."),
    "result_labels": (
        "Provenance-aware human, eval, or model relevance annotations for offline replay; "
        "discounted_gain uses the zero-based log2(position + 2) discount."
    ),
    "content_operations": (
        "One row per terminal fetch operation, tracking input/output counts, duration, and status."
    ),
    "content_fetches": (
        "Individual content fetch items with source type, backend, status, character/word counts, "
        "and window pagination."
    ),
    "content_summaries": (
        "Structured summary outputs from content summarization, capturing model, tokens, "
        "section counts, and source dates."
    ),
    "content_stage_attempts": (
        "One row per extraction stage attempt per fetch item, including skipped stages. "
        "Shows the cascade from Tier-1 resolvers through Jina, local HTTP, Crawl4AI, "
        "Camoufox, and Wayback fallbacks."
    ),
    "content_fetch_items": (
        "Per-fetch-item shaped errors, quality, title, byte counts, redirect/stage-path data, "
        "and diagnostics. One-to-one with content_fetches on terminal_event_id, tool_call_id, and item_index."
    ),
    "content_summary_rungs": (
        "One row per summarization ladder rung tried, including batch and per-item fallback models."
    ),
    "content_backend_health": (
        "Backend liveness probes for remote fetch backends such as Crawl4AI and Camoufox."
    ),
    "analytics_table_freshness": (
        "Heartbeat rows recording the latest recorded timestamp and row count per analytics table."
    ),
    # Derived views
    "vw_events": (
        "Enriched version of the raw event log. Provider name and run key are "
        "coalesced from multiple possible fields so they're always filled in."
    ),
    "vw_quality_events": (
        "Events with their JSON result blobs extracted into named columns. "
        "Use this view to inspect individual search results, rewrites, and sources."
    ),
    "vw_run_timeline": (
        "One row per search run. Shows how many events fired at each stage "
        "(rewrite, rerank, fetch, answer) so you can trace what happened."
    ),
    "vw_provider_results": (
        "One row per search result returned by a provider. "
        "Includes title, URL, snippet, domain, and quality score."
    ),
    "vw_branch_candidates": (
        "When the orchestrator runs multiple query branches in parallel, "
        "each branch's results are recorded here — one row per result per branch."
    ),
    "vw_cache_lookups": (
        "Every time the cache was consulted. Shows hit/miss, how similar the "
        "cached query was (similarity score), its age, and its TTL."
    ),
    "vw_cache_stores": (
        "Every time a result was written into the cache. Shows how large the "
        "stored response was and whether metadata was included."
    ),
    "vw_middleware_events": (
        "Rate limiting and expensive-tool gate events. Shows which tool was "
        "rate-limited, which bucket it hit, and how long it waited."
    ),
    "vw_session_activity": (
        "Session lifecycle events — when sessions start, what tools they use, and when they expire."
    ),
    "vw_content_events": (
        "Web page content extraction events. Shows whether each page was "
        "successfully classified, what extraction method was used, and how large the result was."
    ),
    "vw_error_events": (
        "All error, timeout, and failure events. Includes error type, "
        "HTTP status code if applicable, and the tool/provider that failed."
    ),
    "vw_tool_call_coverage": (
        "Cross-tool overview of request, response, and error event counts, terminal rates, "
        "and duration percentiles."
    ),
    "vw_tool_call_linkage_gaps": (
        "Data linkage diagnostics tracking null rates for tool call IDs, session IDs, trace IDs, "
        "and request fingerprints."
    ),
    "vw_web_search_tool_linkage": (
        "Joins generic web_search tool calls to structured search_runs for linkage gap analysis."
    ),
    "vw_quick_web_search_performance": (
        "Performance metrics for quick_web_search by client model and status: call volume, citations, "
        "duration percentiles, and warning rates."
    ),
    "vw_quick_web_search_citation_sources": (
        "Quick web search citations aggregated by domain and publish date availability."
    ),
    "vw_gemini_search_performance": (
        "Gemini grounded search performance by model, mode, and status: tokens, grounding chunks, "
        "queries, and latencies."
    ),
    "vw_gemini_search_sources": (
        "Grounding sources and URL citations from Gemini searches grouped by source kind and domain."
    ),
    "vw_code_search_provider_yield": (
        "Code search provider yield: total responses, hit volumes, request counts, and latency percentiles."
    ),
    "vw_code_search_hit_sources": (
        "Code search hits broken down by provider, result kind, evidence role, hydration rate, and score."
    ),
    "vw_code_search_variant_effectiveness": (
        "Effectiveness of planner query variants in producing top-ranked code search hits."
    ),
    "vw_code_search_rerank_execution": (
        "Cloud reranker execution metrics for code search: candidate counts and latency."
    ),
    "vw_code_search_diagnostic_patterns": (
        "Failure and diagnostic patterns in code search across providers and failure kinds."
    ),
    "vw_code_search_repository_discovery": (
        "Discovered code repositories by language, verification status, stars, forks, and proof hits."
    ),
    "vw_code_search_score_component_distribution": (
        "Distribution of score components across code search providers and evidence roles."
    ),
    "vw_content_fetch_performance": (
        "Content retrieval performance across fetch backends, source types, and status."
    ),
    "vw_content_summary_output_signals": (
        "Content summary output shape signals: length, entities, key points, tokens, and model breakdown."
    ),
    "vw_content_summary_batch_vs_single": (
        "Comparison of batch versus single content summarization operations and item yields."
    ),
    "vw_content_summary_focus_comparison": (
        "Comparison of summary output signals between focused and unfocused extraction."
    ),
    "vw_content_summary_daily_tokens": (
        "Daily token usage rollups across content summary backends and models."
    ),
    "vw_fetch_stage_funnel": (
        "Fetch stage funnel: attempt counts, outcomes, skipped stages, winning latency, and quality by stage."
    ),
    "vw_fetch_backend_quality": (
        "Fetch backend quality and success rate joined to per-item error and quality data."
    ),
    "vw_fetch_followthrough": (
        "Search-to-fetch follow-through: which fetched URLs appeared in prior search results."
    ),
    "vw_analytics_table_freshness": (
        "Latest heartbeat row per analytics table, showing freshness and row count."
    ),
}
