"""DuckDB-backed analytics store — thin facade over ``analytics.writers``.

Every name previously importable from ``analytics.duckdb_store`` remains
importable from here.  ``duckdb`` and ``settings`` are re-exposed as module
attributes because tests patch them in place.
"""

from __future__ import annotations

import duckdb  # re-exposed for patch.object(duckdb_store.duckdb, ...)

from ..settings import settings  # re-exposed for patch.object(duckdb_store.settings, ...)
from .async_writes import dispatch_duckdb_write
from .writers import *  # noqa: F401,F403  (re-export full public surface)
from .writers import (  # explicit re-export for IDE / static analysis
    TableWriter,
    _ABA_TABLE_NAME,
    _ABE_TABLE_NAME,
    _ABR_TABLE_NAME,
    _ABS_TABLE_NAME,
    _ABV_TABLE_NAME,
    _CE_TABLE_NAME,
    _FR_TABLE_NAME,
    _JE_TABLE_NAME,
    _LLM_CALL_LOG_TABLE_NAME,
    _QUE_TABLE_NAME,
    _LOCK,
    _PC_TABLE_NAME,
    _PH_TABLE_NAME,
    _QE_TABLE_NAME,
    _RC_TABLE_NAME,
    _RS_TABLE_NAME,
    _RUNS_TABLE_NAME,
    _SB_TABLE_NAME,
    _SC_TABLE_NAME,
    _SQS_TABLE_NAME,
    _TC_TABLE_NAME,
    _SUM_ID_TABLE_NAME,
    _SUM_PVD_TABLE_NAME,
    _SUM_QD_TABLE_NAME,
    _SUM_RD_TABLE_NAME,
    _db_path,
    _ensure_ab_assignments,
    _ensure_ab_experiment_variants,
    _ensure_ab_experiments,
    _ensure_ab_results,
    _ensure_ab_shadow_runs,
    _ensure_candidate_embeddings,
    _ensure_columns,
    _ensure_final_results,
    _ensure_judge_calibration_set,
    _ensure_judge_evaluations,
    _ensure_judge_rubrics,
    _ensure_llm_call_log,
    _ensure_query_understanding_events,
    _ensure_llm_judgments,
    _ensure_provider_calls,
    _ensure_provider_health_transitions,
    _ensure_query_embeddings,
    _ensure_rerank_candidates,
    _ensure_rerank_stages,
    _ensure_search_branches,
    _ensure_search_candidates,
    _ensure_search_quality_scores,
    _ensure_search_runs,
    _ensure_tool_calls,
    _ensure_summary_intent_daily,
    _ensure_summary_provider_daily,
    _ensure_summary_quality_daily,
    _ensure_summary_rerank_daily,
    insert_ab_experiment,
    insert_ab_shadow_run,
    insert_candidate_embeddings,
    insert_final_results,
    insert_judge_evaluation,
    insert_llm_call_log,
    insert_query_understanding_event,
    insert_provider_calls,
    ensure_search_quality_tables,
    ensure_store_schema,
    ensure_vss_extension,
    insert_query_embeddings,
    insert_rerank_candidates,
    insert_rerank_stages,
    insert_search_branches,
    insert_search_candidates,
    insert_search_quality_scores,
    insert_search_outcome_batches,
    insert_search_run,
    insert_tool_call_event,
)

__all__ = [
    "TableWriter",
    "_ABA_TABLE_NAME",
    "_ABE_TABLE_NAME",
    "_ABR_TABLE_NAME",
    "_ABS_TABLE_NAME",
    "_ABV_TABLE_NAME",
    "_CE_TABLE_NAME",
    "_FR_TABLE_NAME",
    "_JE_TABLE_NAME",
    "_LLM_CALL_LOG_TABLE_NAME",
    "_QUE_TABLE_NAME",
    "_LOCK",
    "_PC_TABLE_NAME",
    "_PH_TABLE_NAME",
    "_QE_TABLE_NAME",
    "_RC_TABLE_NAME",
    "_RS_TABLE_NAME",
    "_RUNS_TABLE_NAME",
    "_SB_TABLE_NAME",
    "_SC_TABLE_NAME",
    "_SQS_TABLE_NAME",
    "_TC_TABLE_NAME",
    "_SUM_ID_TABLE_NAME",
    "_SUM_PVD_TABLE_NAME",
    "_SUM_QD_TABLE_NAME",
    "_SUM_RD_TABLE_NAME",
    "_db_path",
    "_ensure_ab_assignments",
    "_ensure_ab_experiment_variants",
    "_ensure_ab_experiments",
    "_ensure_ab_results",
    "_ensure_ab_shadow_runs",
    "_ensure_candidate_embeddings",
    "_ensure_columns",
    "_ensure_final_results",
    "_ensure_judge_calibration_set",
    "_ensure_judge_evaluations",
    "_ensure_judge_rubrics",
    "_ensure_llm_call_log",
    "_ensure_query_understanding_events",
    "_ensure_llm_judgments",
    "_ensure_provider_calls",
    "_ensure_provider_health_transitions",
    "_ensure_query_embeddings",
    "_ensure_rerank_candidates",
    "_ensure_rerank_stages",
    "_ensure_search_branches",
    "_ensure_search_candidates",
    "_ensure_search_quality_scores",
    "_ensure_search_runs",
    "_ensure_tool_calls",
    "_ensure_summary_intent_daily",
    "_ensure_summary_provider_daily",
    "_ensure_summary_quality_daily",
    "_ensure_summary_rerank_daily",
    "dispatch_duckdb_write",
    "duckdb",
    "ensure_search_quality_tables",
    "ensure_store_schema",
    "ensure_vss_extension",
    "insert_ab_experiment",
    "insert_ab_shadow_run",
    "insert_candidate_embeddings",
    "insert_final_results",
    "insert_provider_calls",
    "insert_judge_evaluation",
    "insert_llm_call_log",
    "insert_query_understanding_event",
    "insert_query_embeddings",
    "insert_rerank_candidates",
    "insert_rerank_stages",
    "insert_search_branches",
    "insert_search_candidates",
    "insert_search_quality_scores",
    "insert_search_outcome_batches",
    "insert_search_run",
    "insert_tool_call_event",
    "settings",
]

# Legacy aliases for backward compatibility in tests
_ensure_provider_candidates = _ensure_search_candidates
insert_provider_candidates = insert_search_candidates
_ensure_merged_candidates = _ensure_search_candidates
insert_merged_candidates = insert_search_candidates
