"""DuckDB-backed append-only event store for search tuning.

This module is a thin facade over the ``analytics.writers`` subpackage, which
splits the former monolithic store into focused modules:

* ``writers.table_names``   -- ``_*_TABLE_NAME`` constants
* ``writers.connection``    -- ``_LOCK``, ``_db_path``, ``_ensure_columns``
* ``writers.schema``        -- ``_ensure_*`` creators + ``ensure_*`` entrypoints
* ``writers.migrations``    -- legacy ``search_events`` backfill UPDATEs
* ``writers.core``          -- ``TableWriter`` + all ``insert_*`` + ``append_event``

Every name previously importable from ``analytics.duckdb_store`` remains
importable from here, so callers and tests are unaffected.  ``duckdb`` and
``settings`` are re-exposed as module attributes because tests patch them in
place (``patch.object(duckdb_store.duckdb, ...)`` /
``patch.object(duckdb_store.settings, ...)``).
"""

from __future__ import annotations

import duckdb  # re-exposed for patch.object(duckdb_store.duckdb, ...)

from ..settings import settings  # re-exposed for patch.object(duckdb_store.settings, ...)
from .async_writes import dispatch_duckdb_write
from .writers import *  # noqa: F401,F403  (re-export full public surface)
from .writers import (  # explicit re-export for IDE / static analysis
    TableWriter,
    _ABA_TABLE_NAME,
    _ABE_TABLE_NAME,
    _ABR_TABLE_NAME,
    _ABS_TABLE_NAME,
    _ABV_TABLE_NAME,
    _FR_TABLE_NAME,
    _JE_TABLE_NAME,
    _LOCK,
    _MC_TABLE_NAME,
    _PC_TABLE_NAME,
    _PRC_TABLE_NAME,
    _QR_TABLE_NAME,
    _QU_TABLE_NAME,
    _RC_TABLE_NAME,
    _RS_TABLE_NAME,
    _SQS_TABLE_NAME,
    _SUM_ID_TABLE_NAME,
    _SUM_PVD_TABLE_NAME,
    _SUM_QD_TABLE_NAME,
    _SUM_RD_TABLE_NAME,
    _TABLE_NAME,
    _RUNS_TABLE_NAME,
    _db_path,
    _duration_ms_value,
    _ensure_ab_assignments,
    _ensure_ab_experiment_variants,
    _ensure_ab_experiments,
    _ensure_ab_results,
    _ensure_ab_shadow_runs,
    _ensure_columns,
    _ensure_final_results,
    _ensure_judge_evaluations,
    _ensure_merged_candidates,
    _ensure_provider_calls,
    _ensure_provider_candidates,
    _ensure_query_rewrites,
    _ensure_query_understanding,
    _ensure_rerank_candidates,
    _ensure_rerank_stages,
    _ensure_schema,
    _ensure_search_quality_scores,
    _ensure_search_runs,
    _ensure_summary_intent_daily,
    _ensure_summary_provider_daily,
    _ensure_summary_quality_daily,
    _ensure_summary_rerank_daily,
    _event_value,
    _input_count_value,
    _input_tokens_value,
    _int_value,
    _model_used_value,
    _output_count_value,
    _output_tokens_value,
    _phase,
    _provider_value,
    _resolve_ensure,
    _run_key,
    append_event,
    apply_search_events_migrations,
    ensure_search_quality_tables,
    ensure_store_schema,
    insert_ab_experiment,
    insert_ab_shadow_run,
    insert_final_results,
    insert_judge_evaluation,
    insert_merged_candidates,
    insert_provider_calls,
    insert_provider_candidates,
    insert_query_rewrites,
    insert_query_understanding,
    insert_rerank_candidates,
    insert_rerank_stages,
    insert_search_quality_scores,
    insert_search_run,
)

__all__ = [
    "TableWriter",
    "_ABA_TABLE_NAME",
    "_ABE_TABLE_NAME",
    "_ABR_TABLE_NAME",
    "_ABS_TABLE_NAME",
    "_ABV_TABLE_NAME",
    "_FR_TABLE_NAME",
    "_JE_TABLE_NAME",
    "_LOCK",
    "_MC_TABLE_NAME",
    "_PC_TABLE_NAME",
    "_PRC_TABLE_NAME",
    "_QR_TABLE_NAME",
    "_QU_TABLE_NAME",
    "_RC_TABLE_NAME",
    "_RS_TABLE_NAME",
    "_SQS_TABLE_NAME",
    "_SUM_ID_TABLE_NAME",
    "_SUM_PVD_TABLE_NAME",
    "_SUM_QD_TABLE_NAME",
    "_SUM_RD_TABLE_NAME",
    "_TABLE_NAME",
    "_RUNS_TABLE_NAME",
    "_db_path",
    "_duration_ms_value",
    "_ensure_ab_assignments",
    "_ensure_ab_experiment_variants",
    "_ensure_ab_experiments",
    "_ensure_ab_results",
    "_ensure_ab_shadow_runs",
    "_ensure_columns",
    "_ensure_final_results",
    "_ensure_judge_evaluations",
    "_ensure_merged_candidates",
    "_ensure_provider_calls",
    "_ensure_provider_candidates",
    "_ensure_query_rewrites",
    "_ensure_query_understanding",
    "_ensure_rerank_candidates",
    "_ensure_rerank_stages",
    "_ensure_schema",
    "_ensure_search_quality_scores",
    "_ensure_search_runs",
    "_ensure_summary_intent_daily",
    "_ensure_summary_provider_daily",
    "_ensure_summary_quality_daily",
    "_ensure_summary_rerank_daily",
    "_event_value",
    "_input_count_value",
    "_input_tokens_value",
    "_int_value",
    "_model_used_value",
    "_output_count_value",
    "_output_tokens_value",
    "_phase",
    "_provider_value",
    "_resolve_ensure",
    "_run_key",
    "append_event",
    "apply_search_events_migrations",
    "dispatch_duckdb_write",
    "duckdb",
    "ensure_search_quality_tables",
    "ensure_store_schema",
    "insert_ab_experiment",
    "insert_ab_shadow_run",
    "insert_final_results",
    "insert_judge_evaluation",
    "insert_merged_candidates",
    "insert_provider_calls",
    "insert_provider_candidates",
    "insert_query_rewrites",
    "insert_query_understanding",
    "insert_rerank_candidates",
    "insert_rerank_stages",
    "insert_search_quality_scores",
    "insert_search_run",
    "settings",
]
